name: Dependabot auto-merge
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: gh pr review --approve '${{ github.event.pull_request.html_url }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: gh pr merge --auto --squash '${{ github.event.pull_request.html_url }}'
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
